### ISSUE TITLE
Make space pledged visible on UI

### ISSUE THREAD

**Issue by achiurizo** [subspace/substrate-telemetry#18]
We should enable the ability to show how much space was pledged on our frontend, see:

* https://github.com/subspace/block-vote-authorship-collector/blob/f224f50d0c56b1293dbd29a94854e4920e7331c4/src/index.ts#L42-L50
* https://github.com/substrate-developer-hub/substrate-front-end-template/commit/9ae599ecbc37f22608ce98f9120ea4b041847ad8

**Comment by isSerge** [comment]
This will require updating dependencies because currently app uses packages from ~2018, which is not compatible with the current version of polkadot.js API (required to fetch solution ranges from the RPC). There is an [issue](https://github.com/paritytech/substrate-telemetry/issues/459), but there was no progress, unfortunately. Probably I will submit a PR to address this

**Comment by isSerge** [comment]
Submitted [PR](https://github.com/paritytech/substrate-telemetry/pull/498) to the original repository to update frontend

**Comment by isSerge** [comment]
Closed by #20
