### ISSUE TITLE
Show unique reward address count

### ISSUE THREAD

**Issue by achiurizo** [subspace/substrate-telemetry#22]
We should add to the header on telemetry the total unique reward addresses

**Comment by isSerge** [comment]
Currently, there is no easy way to get unique reward addresses since pallet-balances does not allow querying all non-zero balances, and the only way to get unique addresses using node RPC is to query reward extrinsics, which is not very efficient. We could use Subscan API for this (if it is ready), but then we have duplication between telemetry and block explorer.
